### ISSUE TITLE
ur ssh server has been cracked

### ISSUE THREAD

**Issue by lilmond** [coljac/sensie#1]
host: 209.38.22.194 pls change this from easy password

**Comment by lilmond** [comment]
i was doing this to demonstrate ssh hacking on yt, pls change before i upload my content, thanks

**Comment by coljac** [comment]
That's a public server; there's no password, so you didn't hack anything. It's designed to allow anyone in as you can see.

**Comment by lilmond** [comment]
i noticed that, that was kinda cool tho xd, imagne how many people have bee there
